DROP TABLE PROPERTIES;
DROP TABLE CUSTOMERS;
DROP TABLE BROKERS;
DROP TABLE TRANSACTIONS;
DROP TABLE SECURITIES;



CREATE TABLE BROKERS (
	BROKER_ID VARCHAR(6),
	BROKER_PWD VARCHAR(20),
	BROKER_FN VARCHAR(30),
	BROKER_LN VARCHAR(30),
	CONSTRAINT BROKER_PK PRIMARY KEY (BROKER_ID)
	);

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID VARCHAR(6),
	BROKER_ID VARCHAR(6),
	CUSTOMER_PWD VARCHAR(20),
	CUSTOMER_NAME VARCHAR(30),
	CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
	CONSTRAINT CUSTOMER_FK FOREIGN KEY (BROKER_ID) REFERENCES BROKERS(BROKER_ID)
	);
	
CREATE TABLE SECURITIES(
	SECURITY_ID VARCHAR(6),
	SYMBOL VARCHAR(3),
	NAME VARCHAR(30),
	TYPE VARCHAR(20),
	PRICE INT,
	DIVIDEND INT,
	RATING FLOAT,
	HIGH FLOAT,
	LOW FLOAT,
	CONSTRAINT SECURITIES_PK PRIMARY KEY (SECURITY_ID)
);
	
	
CREATE TABLE PROPERTIES(
	PROPERTY_ID VARCHAR(6),
	CUSTOMER_ID VARCHAR(6),
	SECURITY_ID VARCHAR(6),
	SHARED_OWNED INTEGER,
	CONSTRAINT PROPERTIES_PK PRIMARY KEY (PROPERTY_ID),
	CONSTRAINT PROPERTIES_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
	CONSTRAINT PROPERTIES_FK2 FOREIGN KEY (SECURITY_ID) REFERENCES SECURITIES(SECURITY_ID)
	);
	
CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID VARCHAR(6),
	TRANS_DATE DATE,
	TRANS_TIME TIME,
	VALUE INT,
	PASS_FAIL BOOLEAN,
	TYPE VARCHAR(5),
	CONSTRAINT TRANSACTIONS_PK PRIMARY KEY (TRANSACTION_ID)
);

INSERT INTO SECURITIES VALUES('S44X67','MMX','Meow Mix Foods', 'Stock',132.75, 3, 4.2, 3.10, 5.50);
INSERT INTO SECURITIES VALUES('S52I78','GAT','International Gato Systems','Stock',62.00, 1, 2.1, 5.50, 7.10);
INSERT INTO SECURITIES VALUES('S91Y84','FOO','FooBar Solutions', 'Stock',9.50, 0, 3.6, 4.78, 6.12);
 
INSERT INTO BROKERS VALUES('B12345', 'abcd', 'Bee', 'Mayes');
INSERT INTO BROKERS VALUES('B12346', 'efgh', 'Molly', 'Vonada');
INSERT INTO BROKERS VALUES('B12347', 'ijkl', 'Shaughn', 'Seepaul');
INSERT INTO BROKERS VALUES('B12348', 'mnop', 'Dre', 'Williams');

INSERT INTO CUSTOMERS VALUES('C12345', 'B12345', 'ABCD', 'Bank of America');
INSERT INTO CUSTOMERS VALUES('C12346', 'B12346', 'EFGH', 'Leonardo DiCaprio');

COMMIT;